nav:
  - About: index.md
  - Core Knowledge & Theory:
      - Security and Risk Management:
          - The CIA Triad and DAD Triad: core-knowledge-and-theory/security-and-risk-management/the-cia-triad-and-dad-triad.md
      - Asset Security:
          - Data Classification: core-knowledge-and-theory/asset-security/data-classification.md
      - Security Architecture and Engineering:
          - Cryptography: core-knowledge-and-theory/security-architecture-and-engineering/cryptography.md
      - Communication and Network Security:
          - OSI and TCP/IP Models: core-knowledge-and-theory/communication-and-network-security/osi-and-tcp-ip-models.md
remote_branch: docs
site_name: Harckives
theme:
  name: readthedocs
